---
title: How rOpenSci performs peer-review
author: Mauro Lepore 
date: https://github.com/maurolepore/ropensci-review
output: ioslides_presentation
---

## Outline

* Introduction
  * About you and me
  * Why peer-review? 
  * Why this talk?
  
* Two crucial components
  * The way we communicate.
  * The way we build and review software.

* Wrap up
  * Takeaways.
  * Questions and comments.

# Introduction

## About you and me

About you:

* You may want to be an author, reviewer, or editor.

About me:

* I build tools to support research in green finance.
* Before I was a biologist.
* I joined rOpenSci in 2018 and played different roles.

## [Why peer-review?](https://github.com/ropensci/software-review?tab=readme-ov-file#why-and-how-submit-your-package-to-ropensci)

## Why this talk?

The process is complex and can feel overwhelming.

This talk:

* Highlights the most important materials.
* Shows you where you can find the rest.
* Gives you the chance to ask questions.

# Two crucial components

## Two crucial components

* The way we communicate: [Code of conduct](https://ropensci.org/code-of-conduct/).
* The way we build and review software: ["Devguide"](https://devguide.ropensci.org/).

> "[Helping to improve software] in a kind and respectful way is just as important as the technical aspect".  
> -- Yanina Bellini Saibene

## Be kind and respectful

[Example of a kind and respectful reviewer's response](https://github.com/ropensci/software-review/issues/577#issuecomment-1494333794).

> "It's like when I hold the door open for someone."  
> "Even when someone volunteers their time, there is a cost of their time and effort."  
> -- [Setting expectations for open source
participation](https://snarky.ca/setting-expectations-for-open-source-participation/amp/)

## The way we build and review software

Guide for authors

* [Package categories in scope for rOpenSci review](https://devguide.ropensci.org/softwarereview_policies.html#package-categories).
* [Guide to building a package](https://devguide.ropensci.org/building.html).
* [Guide to submitting a package](https://devguide.ropensci.org/authors-guide.html).
* [Choose between different types of submission](https://github.com/ropensci/software-review/issues/new/choose).

Other guides, templates, and tools

* [Guide for reviewers](https://devguide.ropensci.org/reviewerguide.html) and [editors](https://devguide.ropensci.org/editorguide.html).
* [Template for reviewers](https://devguide.ropensci.org/reviewtemplate.html) and [editors](https://devguide.ropensci.org/editortemplate.html).
* [Bot commands](https://devguide.ropensci.org/bot_cheatsheet.html).

# Wrap up

## Takeaways

* Be kind and respectful.
* The process is complex but you'll find lots of help.

## Questions and comments?

Thank you!

Mauro | maurolepore@gmail.com

